### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by SharkChips**
I found a few bugs, so I squashed them. If some of the code is slightly unreadable let me know.

### CODE REVIEW

**Comment by kiefferbp** [comment]
Ha. Good one. By the way, there's a significantly easier way to crack my extension than this. I am not sure why your cracking method is so convoluted (assuming it even works---your "hack website" commit looks fishy as hell, so I don't care to check).

I am also working on server-side features that'll also perform server-side license checks, so this crack won't work there. It may even get your IP blacklisted. :)

**Comment by SharkChips** [comment]
No worries! I just wanted to point them out (I've actually bought the license). 

Anyways, thanks for making bing pong!

**Comment by ZakariaRidouh** [comment]
Uhh, did @SharkChips just try to merge a cracked version of BPH?

**Comment by kiefferbp** [comment]
Yep, and he "tried" to disguise his changes as fixes. I am not sure who he's trying to fool.

**Comment by kiefferbp** [comment]
BTW, @SharkChips, your commit 9907a8013ac7e6ceaa4e74aba16735d2f567a5a has a major flaw in it. Can you find it?

**Comment by SharkChips** [comment]
@kiefferbp Yes whoops! I forgot to add isLicensed = true; before line 43! My bad! :)

**Comment by ZakariaRidouh** [comment]
@SharkChips Why are you trying to crack BPH if you've "actually bought the license"?

**Comment by SharkChips** [comment]
@ZakariaRidouh I just wanted to bring these holes to @kiefferbp 's attention, and I thought a pull request would be funny :)

**Comment by kiefferbp** [comment]
@SharkChips I see. That's fine then. :)

**Pull request closed without merging**
